//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearthstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public string guid { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public string local { get; set; }
        public string type { get; set; }
        public string faction { get; set; }
        public string rarity { get; set; }
        public Nullable<int> cost { get; set; }
        public string race { get; set; }
        public string playerClass { get; set; }
        public string text { get; set; }
        public string inPlayText { get; set; }
        public string mechanics { get; set; }
        public string flavor { get; set; }
        public string artist { get; set; }
        public Nullable<int> attack { get; set; }
        public Nullable<int> health { get; set; }
        public Nullable<bool> collectible { get; set; }
        public string elite { get; set; }
        public string howToGet { get; set; }
        public string howToGetGold { get; set; }
        public string img { get; set; }
        public string imgGold { get; set; }
        public string set { get; set; }
    }
}
